apiVersion: v1
kind: ServiceAccount
metadata:
  name: env-sba-sa
  namespace: env-sba
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: env-sba-spring-cloud
  namespace: env-sba
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets", "pods", "services", "endpoints"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: env-sba-spring-cloud
  namespace: env-sba
subjects:
  - kind: ServiceAccount
    name: env-sba-sa
    namespace: env-sba
roleRef:
  kind: Role
  name: env-sba-spring-cloud
  apiGroup: rbac.authorization.k8s.io
